{
 "title": "Job Detail - Prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cluster", "query": "prometheus" },
   {
    "name": "projectName",
    "label": "ProjectName",
    "query": {
     "query": "label_values(proc_cpu_use,project_name)"
    }
   },
   {
    "name": "instance",
    "label": "Instance ID",
    "query": {
     "query": "label_values(node_cpu_use_percent,instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(proc_cpu_use{instance_id=~\"$instance\"},instance)"
    }
   },
   { "name": "cusInterval", "label": "Interval", "query": "10s, 30s, 1m, 5m, 15m" }
  ]
 },
 "panels": [
  { "title": "Job Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_pid",
     "expr": "proc_cpu_use{instance=~\"$job\", project_name=~\"$projectName\", instance_id=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$cusInterval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "proc_cpu_use",
     "query": "SELECT \"cpu_use\" FROM \"proc_cpu_use\" WHERE (\"instance_type\" =~ /^$InstanceType$/ AND \"project_name\" =~ /^$ProjectName$/) AND $timeFilter GROUP BY \"pid\"",
     "select": [
      [
       { "params": [ "cpu_use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$ProjectName$/" },
      { "condition": "AND", "key": "pid", "operator": "=~", "value": "/^$JobName$/" }
     ]
    }
   ]
  },
  {
   "title": "Mem Use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_pid",
     "expr": "proc_mem_use{instance=~\"$job\", instance_id=~\"$instance\", project_name=~\"$projectName\"}",
     "groupBy": [
      { "params": [ "$cusInterval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "proc_mem_use",
     "select": [
      [
       { "params": [ "mem_use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$ProjectName$/" },
      { "condition": "AND", "key": "pid", "operator": "=~", "value": "/^$JobName$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_pid",
     "expr": "proc_disk_use{instance=~\"$job\", instance_id=~\"$instance\", project_name=~\"$projectName\"}",
     "groupBy": [
      { "params": [ "$cusInterval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "proc_disk_use",
     "select": [
      [
       { "params": [ "disk_use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$ProjectName$/" },
      { "condition": "AND", "key": "pid", "operator": "=~", "value": "/^$JobName$/" }
     ]
    }
   ]
  },
  { "title": "Compute Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Use",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "node_cpu_use_percent{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$cusInterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "node_cpu_use",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$instanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Mem Use",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "mem_used_per{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$cusInterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "node_mem_use",
     "select": [
      [
       { "params": [ "mem_used_per" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$instanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "disk_used_per{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$cusInterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "node_disk_use",
     "select": [
      [
       { "params": [ "disk_used_per" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$instanceId$/" }
     ]
    }
   ]
  }
 ]
}