{
 "title": "Job Overview - Prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cluster", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(proc_cpu_use,instance)"
    }
   },
   { "name": "cusInterval", "label": "Interval", "query": "10s, 30s,1m, 5m,10m, 15m" }
  ]
 },
 "panels": [
  {
   "title": "CPU Use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_pid",
     "expr": "proc_cpu_use{instance=~\"$job\"}",
     "groupBy": [
      { "params": [ "$cusInterval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "proc_cpu_use",
     "query": "SELECT \"cpu_use\" FROM \"proc_cpu_use\" WHERE (\"pid\" =~ /^$job$/) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "cpu_use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pid", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Mem Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_pid",
     "expr": "proc_mem_use{instance=~\"$job\"}",
     "groupBy": [
      { "params": [ "$cusInterval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "proc_mem_use",
     "select": [
      [
       { "params": [ "mem_use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pid", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_pid",
     "expr": "proc_disk_use{instance=~\"$job\"}",
     "groupBy": [
      { "params": [ "$cusInterval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "proc_disk_use",
     "select": [
      [
       { "params": [ "disk_use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pid", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  }
 ]
}